### ISSUE TITLE
建议分析第三方库带上版本号

### ISSUE THREAD

**Issue by ainopara** [Draveness/iOS-Source-Code-Analyze#1]
据我所知，Alamofire早期是有过把所有内容都放到一个名为Alamofire的class中的实现的。随着Swift的发展，Alamofire的实现方式也在不断变化。
加上版本号，可以让读者知道分析是基于哪个第三方库的版本进行的。

**Comment by Draveness** [comment]
前面的那些写的都比较早了，版本号基本都忘了，不过 Alamofire 这个下面的 blog 会更改

**Comment by Draveness** [comment]
后面这些我都加上吧
