### ISSUE TITLE
AFNetworking 中似乎有一个注释写错了

### ISSUE THREAD

**Issue by rxg9527** [Draveness/iOS-Source-Code-Analyze#17]
《AFNetworking 的核心 AFURLSessionManager（二）》一文中的
### 代理方法 `URLSession:task:didCompleteWithError:`

在每一个 `NSURLSessionTask` 结束时，都会在代理方法 `URLSession:task:didCompleteWithError:` 中：

1. 调用传入的 `completionHander` block
2. 发出 `AFNetworkingTaskDidCompleteNotification` 通知

```source-objc
- (void)URLSession:(__unused NSURLSession *)session
              task:(NSURLSessionTask *)task
didCompleteWithError:(NSError *)error
{
    #1：获取数据, 存储 `responseSerializer` 和 `downloadFileURL`

    if (error) {
        #2：在存在错误时调用 `completionHandler`
    } else {
        #3：调用 `completionHandler`
    }
}
```

其中代码段中的#1的『存储responseSerializer』是否应该是『存储responseData』?

**Comment by Draveness** [comment]
这里没错

**Comment by Draveness** [comment]
你可以找下源代码
