### ISSUE TITLE
SDWebImage 找缓存的图片的问题

### ISSUE THREAD

**Issue by liuxu0718** [Draveness/iOS-Source-Code-Analyze#19]
如果内存中没找到就去disk里找，请问图片是怎么进入到disk中的.....

**Comment by yunshuipiao** [comment]
第一次请求数据时，内存缓存没有数据，硬盘缓存也没有。
当服务器返回数据时，当如下处理：
1. 使用服务器的数据（解析）
2. 将服务器的数据存储到硬盘
此时缓存情况：（内存硬盘皆有）

再次请求数据分为两种情况：
（1）如果程序并没有被关闭，一直在运行
那么此时内存缓存中有数据，硬盘缓存中有数据。如果此时再次请求数据，直接使用内存缓存中的数据即可
（2）如果程序重新启动
那么此时内存缓存已经消失，没有数据，硬盘缓存依旧存在，还有数据。如果此时再次请求数据，需要读取内存中缓存的数据。
提示：从硬盘缓存中读取数据后，内存缓存中又有数据了

**Comment by wang111588** [comment]
说实话，文章质量还需要提高。我看的不多，看到的部分感觉没有说到点上。

**Comment by Draveness** [comment]
@wang111588 在哪里没有说到点子，如何提高呢？

**Comment by yunshuipiao** [comment]
@wang111588  对啊，我也想知道哪里没有说到点子上.

**Comment by JakeLin** [comment]
我觉得博主很用心，写得很好，@Draveness 谢谢👍👍👍

**Comment by Draveness** [comment]
多谢🌚
