### ISSUE TITLE
请问可运行的Runtime工程哪里可以下载到？

### ISSUE THREAD

**Issue by shz2050** [Draveness/iOS-Source-Code-Analyze#21]
如题~
万分感谢~！

**Comment by Draveness** [comment]
https://github.com/Draveness/iOS-Source-Code-Analyze/tree/master/contents/objc 这里的 README 有链接

**Comment by shz2050** [comment]
我是用的这个工程，但是在Xcode8.0好像编译不过。请问你可以不？

**Comment by lanvsblue** [comment]
@shz2050 可运行版本: https://github.com/lanvsblue/objc4-706
