### ISSUE TITLE
BlocksKit 在ipad上面会崩溃

### ISSUE THREAD

**Issue by hhb19900618** [Draveness/iOS-Source-Code-Analyze#23]

**Comment by Draveness** [comment]
这跟我有关系么？？？

**Comment by hhb19900618** [comment]
我在这里链接 看到你的 http://www.cocoachina.com/ios/20160505/16112.html
请问你这个项目不是blockkit吗

**Comment by Draveness** [comment]
。。。。不是

**Comment by Draveness** [comment]
https://github.com/zwaldowski/BlocksKit

**Comment by youngshook** [comment]
@hhb19900618 
可以尝试在 Podfile 中添加，看看是否能结局你的问题。

pre_install do
    #Fix: BlocksKit bug, A2DynamicUITextFieldDelegate Class can cause infinite recursive calls with system class EditUserWordController.
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system("sed -i '' '/UIWebView/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm -f Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h 2>/dev/null')
    system('rm -f Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m 2>/dev/null')
    system('rm -f Pods/BlocksKit/BlocksKit/UIKit/UIWebView+BlocksKit.h 2>/dev/null')
    system('rm -f Pods/BlocksKit/BlocksKit/UIKit/UIWebView+BlocksKit.m 2>/dev/null')
end
