### ISSUE TITLE
可运行的runtime源码工程可以放出来吗？

### ISSUE THREAD

**Issue by mleasyZhuZhiqiang** [Draveness/iOS-Source-Code-Analyze#24]
[runtime源码工程](https://opensource.apple.com/tarballs/objc4/objc4-706.tar.gz)很好下，可是苦于运行不起来。
如果能够调试runtime源代码，是最好的学习方式了。

**Comment by dnnta** [comment]
可以试试这个 https://github.com/RetVal/objc-runtime

**Comment by liuzhiyi1992** [comment]
@dnnta 运行不起来

**Comment by lanvsblue** [comment]
@liuzhiyi1992 706版本的runtime https://github.com/lanvsblue/objc4-706

**Comment by liuzhiyi1992** [comment]
@lanvsblue 感谢，主要是需要更新到Sierra
