### ISSUE TITLE
「从源代码看 ObjC 中消息的发送」这篇文章的两个问题

### ISSUE THREAD

**Issue by kylinroc** [Draveness/iOS-Source-Code-Analyze#25]
1

> 不过 `cache_getImp` 的实现目测是不开源的，同时也是汇编写的，在我们尝试 step in 的时候进入了如下的汇编代码。
>
> 它会进入一个 `CacheLookup` 的标签，获取实现，使用汇编的原因还是因为要加速整个实现查找的过程，其原理推测是在类的 cache 中寻找对应的实现，只是做了一些性能上的优化。

`CacheLookup` 宏的定义就在[这里](https://github.com/RetVal/objc-runtime/blob/master/runtime/Messengers.subproj/objc-msg-x86_64.s#L341)。

2

> 我们如何确定 `objc_msgSend` 的实现到底是什么呢？其实我们没有办法来确认它的实现，因为这个函数的实现使用汇编写的，并且实现是不开源的。
>
> 不过，我们需要确定它是否真的**访问了类中的缓存**来加速实现寻找的过程。

`objc_msgSend` 的实现也能在[这里](https://github.com/RetVal/objc-runtime/blob/master/runtime/Messengers.subproj/objc-msg-x86_64.s#L693)看到，并且的确查找了缓存。文章最后的实验就显得有点鸡肋了。

**Comment by Draveness** [comment]
👍
