### ISSUE TITLE
Objective-C 中 load 方法的问题

### ISSUE THREAD

**Issue by HaloWang** [Draveness/iOS-Source-Code-Analyze#3]
[神奇的 BlocksKit （二）- UITextField+BlocksKit 分类和 load 方法](https://github.com/Draveness/iOS-Source-Code-Analyze/blob/master/BlocksKit/%E7%A5%9E%E5%A5%87%E7%9A%84%20BlocksKit%20%EF%BC%88%E4%BA%8C%EF%BC%89.md#uitextfieldblockskit-分类和-load-方法)

> 为什么在 load 方法中调用这两个方法？原因有两个：

> - 该方法只会调用一次，减少了调用的次数
> - 该方法只会在文件被引用的时候调用，减少了不必要的动态代理注册等一系列步骤

什么叫做『在文件被引用的时候调用』啊？
好像是所有被编译的 Category 都会调用一次的吧？
而且 Category 不用引用`.h`，只要`SomeClass+CategoryName.m`被编译了，就会调用 Category 中实现的`+load`方法啊？

**Comment by Draveness** [comment]
1. 文件并不是被编译时调用的 load 方法，load 方法的调用是在运行时调用

**Comment by HaloWang** [comment]
好吧，我知道 `+load` 方法是在应用应用初始化所有类的时候调用的，反正不管怎么说，`+load` 就是 ObjC 最好的黑魔法的入口方法了吧😅

**Comment by Draveness** [comment]
一般与 load 进行比较的方法都是 initialize, 这里没有进行说明，因为这种文章太多了

> There are two methods that are automatically invoked by the Objective-C runtime for each class. +load is sent when the class is initially loaded, while +initialize is called just before the application calls its first method on that class or an instance of that class. Both are optional, and are executed only if the method is implemented.
> Because method swizzling affects global state, it is important to minimize the possibility of race conditions. +load is guaranteed to be loaded during class initialization, which provides a modicum of consistency for changing system-wide behavior. By contrast, +initialize provides no such guarantee of when it will be executed—in fact, it may never be called, if that class is never messaged directly by the app.

[Method Swizzling](http://nshipster.com/method-swizzling/)
