### ISSUE TITLE
图片404

### ISSUE THREAD

**Issue by qmkCamel** [Draveness/iOS-Source-Code-Analyze#5]
![image](https://cloud.githubusercontent.com/assets/5952752/14841732/6a05b10e-0c73-11e6-828c-04b37142e26f.png)

**Comment by Draveness** [comment]
哪篇文章的图片啊

**Comment by qmkCamel** [comment]
iOS 源代码分析 --- SDWebImage

**Comment by wosta** [comment]
iOS 源代码分析 --- SDWebImage 图片挂了

**Comment by Draveness** [comment]
这个问题。。我可能暂时解决不了，因为时间比较久了，我过几天再画一个吧

**Comment by chaoskyme** [comment]
@Draveness SDWebImage的框架图还有吗，图破了

**Comment by Draveness** [comment]
找不到了 @chaoskyme
