### ISSUE TITLE
请问作者是通过什么方法输出调用堆栈的？

### ISSUE THREAD

**Issue by HaloWang** [Draveness/iOS-Source-Code-Analyze#6]
[AFNetworking 的调用栈](https://github.com/Draveness/iOS-Source-Code-Analyze/blob/master/AFNetworking/AFNetworking%20%E6%A6%82%E8%BF%B0%EF%BC%88%E4%B8%80%EF%BC%89.md#afnetworking-的调用栈)

> ```
> - [AFHTTPSessionManager initWithBaseURL:]
>     - [AFHTTPSessionManager initWithBaseURL:sessionConfiguration:]
>         - [AFURLSessionManager initWithSessionConfiguration:]
>             - [NSURLSession sessionWithConfiguration:delegate:delegateQueue:]
>             - [AFJSONResponseSerializer serializer] // 负责序列化响应
>             - [AFSecurityPolicy defaultPolicy] // 负责身份认证
>             - [AFNetworkReachabilityManager sharedManager] // 查看网络连接情况
>         - [AFHTTPRequestSerializer serializer] // 负责序列化请求
>         - [AFJSONResponseSerializer serializer] // 负责序列化响应
> ```

**Comment by Draveness** [comment]
分析的，不是输出的
